shared:
    image: node:6
jobs:
    # the main job is run in pull requests as well
    main:
        steps: 
            - echo: echo "fail"
---
version: 4
shared:
    image: node:6
jobs:
    # the main job is run in pull requests as well
    main:
        steps: 
            - echo: echo "passed"
