shared:
    image: node:8
jobs:
    # the main job is run in pull requests as well
    main:
        requires: [~commit]
        steps: 
            - install: npm install screwdriver-template-main
            - validate: ./node_modules/.bin/template-validate
            - publish: ./node_modules/.bin/template-publish
    tag:
        requires: [main]
        steps:
            - install: npm install screwdriver-template-main
            - token: echo $SD_TOKEN
            - tag: ./node_modules/.bin/template-tag --name tifftemplate --version 1.0.4 --tag latest
    use-tag:
        requires: [tag]
        template: tifftemplate@latest
