shared:
    image: node:6
jobs:
    # the main job is run in pull requests as well
    main:
        steps: 
            - echo: echo "fail"
---
version: 4
shared:
    image: node:6
jobs:
    # the main job is run in pull requests as well
    main:
        requires: [~pr, ~commit]
        steps: 
            - echo: echo $SD_PULL_REQUEST
    a:
        requires: [main]
        steps:
            - echo: echo hello
    b:
        requires: [main]
        steps:
            - echo: echo hello
    c:
        requires: [a, b]
        steps:
            - echo: echo bye
