#shared:
#    image: node:6
#jobs:
#    # the main job is run in pull requests as well
#    main:
#        steps: 
#            - install: npm install screwdriver-template-main
#            - validate: ./node_modules/.bin/template-validate
#            - publish: ./node_modules/.bin/template-publish
#    tag:
#        steps:
#            - install: npm install screwdriver-template-main
#            - token: echo $SD_TOKEN
#            - tag: ./node_modules/.bin/template-tag --name tifftemplate --version 1.0.4 --tag latest
#    use-tag:
#        template: tifftemplate@latest
---
version: 4
shared:
    image: node:6
jobs:
    main:
        # annotations: 
        #     beta.screwdriver.cd/executor: queue
        steps:
            - begin_time:  START=$(date +'%s') && meta set time.start $START && echo $START
            # - sleep: sleep 1000
            - save_hello: echo hello > $SD_ARTIFACTS_DIR/hello.txt
            - save_hi: echo hi > $SD_ARTIFACTS_DIR/hi.txt
            - save_bye: echo bye > $SD_ARTIFACTS_DIR/bye.txt
            - save_goodbye: echo goodbye > $SD_ARTIFACTS_DIR/goodbye.txt
            - end_time:  END=$(date +'%s') && meta set time.end $END && echo $END
            - print_time: DIFF=$(($END - $START)) && echo $DIFF
            - send_receipt: npm install request && node api.js
